lab5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('theApp/', include("theApp.urls"))
]

theApp/urls.py
from django.urls import path
from . import views
app_name="theApp"
urlpatterns=[
    path("add", views.add, name="add"),
    path("", views.index, name="index")
]

theApp/models.py
from django.db import models

# Create your models here.

theApp/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

people = []

class Person:
    def __init__(self, username, password):
        self.username = username
        self.password = password

    def __str__(self):
        return self.username

class PersonForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(widget=forms.PasswordInput(), label="Password")

def add(request):
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            new_person = Person(username, password)
            people.append(new_person)
            return HttpResponseRedirect(reverse("theApp:index"))
    else:
        form = PersonForm()

    return render(request, "theApp/add.html", {"form": form})

def index(request):
    return render(request, "theApp/index.html", {"people": people})

theApp/templates/theApp/add.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
  
    
    <title>adding people</title>
    <link rel="stylesheet" href="{% static 'theApp/styles.css' %}">
</head>
<body>
<h1>Add username and password</h1>
<form action="{% url 'theApp:add' %}" method="post">
    {% csrf_token %}
    {{ form.as_p  }}
    <input type="submit" value="Submit">
</form>
<a href="{% url 'theApp:index' %}">The name of the persons</a>    
</body>
</html>

theApp/templates/theApp/index.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
  
    
    <title>All people</title>
    <link rel="stylesheet" href="{% static 'theApp/styles.css' %}">
</head>
<body>
  <h1>All people</h1>
  <ul>
    {% for person in people %}
        <li>{{ person.username }}</li>
    {% endfor %}
  </ul>
  <a href="{% url 'theApp:add' %}">Add Person</a>
    
</body>
</html>